feat: add latest tag

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -13,14 +13,17 @@ jobs:
             context: ./runtime
             dockerfile: ./runtime/Dockerfile.no-package
             tag: ghcr.io/codefuse-ai/runtime:0.1.0
+            tag_latest: ghcr.io/codefuse-ai/runtime:latest
           - name: ekgfrontend
             context: .
             dockerfile: ./Dockerfile_frontend
             tag: ghcr.io/codefuse-ai/ekgfrontend:0.1.0
+            tag_latest: ghcr.io/codefuse-ai/ekgfrontend:latest
           - name: ekgservice
             context: .
             dockerfile: ./Dockerfile_gh
             tag: ghcr.io/codefuse-ai/ekgservice:0.1.0
+            tag_latest: ghcr.io/codefuse-ai/ekgservice:latest
 
     steps:
       - name: Checkout code
@@ -38,6 +41,88 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}  # 使用当前 GitHub 用户名
           password: ${{ secrets.CR_TOKEN }}  # 使用您刚刚添加的个人访问令牌
+
+      - name: Build and push with retry for amd64
+        run: |
+          max_retries=5
+          count=0
+          success=false
+
+          while [[ $count -lt $max_retries ]]; do
+            echo "Attempt $(($count + 1)) of $max_retries..."
+            docker build --push \
+              --platform linux/amd64 \
+              --tag ${{ matrix.image.tag }}-amd64 \
+              --tag ${{ matrix.image.tag_latest }}-amd64 \
+              -f ${{ matrix.image.dockerfile }} ${{ matrix.image.context }} && success=true && break
+            
+            count=$(($count + 1))
+            echo "Build failed, retrying in 5 seconds..."
+            sleep 15
+          done
+
+          if [ "$success" = false ]; then
+            echo "Build failed after $max_retries attempts."
+            exit 1
+          fi
+
+      - name: docker image for amd64
+        run: |
+          df -h
+          docker images
+          docker rmi ${{ matrix.image.tag }}-amd64
+          docker rmi ${{ matrix.image.tag_latest }}-amd64
+          df -h
+          docker images
+
+      - name: Build and push with retry for arm64
+        run: |
+          max_retries=5
+          count=0
+          success=false
+
+          while [[ $count -lt $max_retries ]]; do
+            echo "Attempt $(($count + 1)) of $max_retries..."
+            docker build --push \
+              --platform linux/arm64 \
+              --tag ${{ matrix.image.tag }}-arm64 \
+              --tag ${{ matrix.image.tag_latest }}-arm64 \
+              -f ${{ matrix.image.dockerfile }} ${{ matrix.image.context }} && success=true && break
+            
+            count=$(($count + 1))
+            echo "Build failed, retrying in 5 seconds..."
+            sleep 15
+          done
+
+          if [ "$success" = false ]; then
+            echo "Build failed after $max_retries attempts."
+            exit 1
+          fi
+
+      - name: docker image for arm64
+        run: |
+          df -h
+          docker images
+          docker rmi ${{ matrix.image.tag }}-arm64
+          docker rmi ${{ matrix.image.tag_latest }}-arm64
+          df -h
+          docker images
+
+      - name: docker manifest
+        run: |
+          docker images
+          
+          docker manifest create ${{ matrix.image.tag }} ${{ matrix.image.tag }}-arm64 ${{ matrix.image.tag }}-amd64
+          docker manifest create ${{ matrix.image.tag_latest }} ${{ matrix.image.tag_latest }}-arm64 ${{ matrix.image.tag_latest }}-amd64
+          
+          docker manifest inspect ${{ matrix.image.tag }}
+          docker manifest inspect ${{ matrix.image.tag_latest }}
+          
+          docker manifest push ${{ matrix.image.tag }}
+          docker manifest push ${{ matrix.image.tag_latest }}
+
+      - name: Check disk space
+        run: df -h
 
       # - name: docker image
       #   run: |
@@ -67,80 +152,3 @@ jobs:
       #     push: true
       #     tags: ${{ matrix.image.tag }}-amd64
       #     platforms: linux/amd64
-
-      - name: Build and push with retry for amd64
-        run: |
-          max_retries=5
-          count=0
-          success=false
-
-          while [[ $count -lt $max_retries ]]; do
-            echo "Attempt $(($count + 1)) of $max_retries..."
-            docker build --push \
-              --platform linux/amd64 \
-              --tag ${{ matrix.image.tag }}-amd64 \
-              -f ${{ matrix.image.dockerfile }} ${{ matrix.image.context }} && success=true && break
-            
-            count=$(($count + 1))
-            echo "Build failed, retrying in 5 seconds..."
-            sleep 15
-          done
-
-          if [ "$success" = false ]; then
-            echo "Build failed after $max_retries attempts."
-            exit 1
-          fi
-
-      - name: docker image for amd64
-        run: |
-          df -h
-          docker images
-
-      # - name: Build and push amr64
-      #   uses: docker/build-push-action@v2
-      #   with:
-      #     context: ${{ matrix.image.context }}
-      #     file: ${{ matrix.image.dockerfile }}
-      #     push: true
-      #     tags: ${{ matrix.image.tag }}-arm64
-      #     platforms: linux/arm64
-
-      - name: Build and push with retry for arm64
-        run: |
-          max_retries=5
-          count=0
-          success=false
-
-          while [[ $count -lt $max_retries ]]; do
-            echo "Attempt $(($count + 1)) of $max_retries..."
-            docker build --push \
-              --platform linux/arm64 \
-              --tag ${{ matrix.image.tag }}-arm64 \
-              -f ${{ matrix.image.dockerfile }} ${{ matrix.image.context }} && success=true && break
-            
-            count=$(($count + 1))
-            echo "Build failed, retrying in 5 seconds..."
-            sleep 15
-          done
-
-          if [ "$success" = false ]; then
-            echo "Build failed after $max_retries attempts."
-            exit 1
-          fi
-
-      - name: docker image for arm64
-        run: |
-          df -h
-          docker images
-
-      - name: docker manifest
-        run: |
-          docker images
-          docker manifest inspect ${{ matrix.image.tag }}-arm64
-          docker manifest inspect ${{ matrix.image.tag }}-amd64
-          docker manifest create ${{ matrix.image.tag }} ${{ matrix.image.tag }}-arm64 ${{ matrix.image.tag }}-amd64
-          docker manifest inspect ${{ matrix.image.tag }}
-          docker manifest push ${{ matrix.image.tag }}
-
-      - name: Check disk space
-        run: df -h
